server:
  port: 8081
  servlet:
    context-path:    

spring:
  datasource:
    url: ${DBMD_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:rooy}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "LNoSyo0dt7Y603iqmCRPxohK23cMcAtyHNmTsviwFqRuAl1GCPKkcUOGUmZvw/cM"

